### PR TITLE
Adds logging

### PR DESCRIPTION
**Pull request by caio-galvao**

### CODE REVIEW

**Comment by gabrielfelipeg** [comment]
This is not logging. You create a function that prints the output. You should see [this](https://docs.python.org/3/howto/logging.html), the issue asks to remove the print, but the prints in the code are the output and some execution metrics. I propose that this issue mutates into two different issues.

**Comment by gabrielfelipeg** [comment]
I recommend renaming this PR and starting to focus on issue #18.

**Review by gabrielfelipeg — CHANGES_REQUESTED** [review]
Could you change the suggestions cited above?

**Comment by caio-galvao** [comment]
Ok

**Pull request closed without merging**
